### ISSUE TITLE
Doesn't Unmarshal padded base64 encoded strings  

### ISSUE THREAD

**Issue by apryiomka** [bas-d/appattest#2]
Looking at apple attest API docs, there is no requirement to use un-padded encoding: 
```
guard let clientData = try? JSONEncoder().encode(request) else { return }
let clientDataHash = Data(SHA256.hash(data: clientData))
```

But the padded encoding fails to unmarshal due to the `RawURLEncoding` being used: https://github.com/bas-d/appattest/blob/master/utils/base64.go#L19-L20

For instance, i have `clientData` that is encoded with `base64.URLEncoding`, it now fails to decode with `base64.RawURLEncoding.Decode`:

```
encodedStr := base64.URLEncoding.EncodeToString([]byte("1234"))
ddd := bytes.Trim([]byte(encodedStr), "\"")
out := make([]byte, base64.RawURLEncoding.DecodedLen(len(ddd)))
n, err := base64.RawURLEncoding.Decode(out, ddd)
if err != nil {
    t.Error(err)
}
fmt.Println(n)
```

**Comment by bas-d** [comment]
The reason `RawURLEncoding` is used, is that it is based on the WebAuthn spec, which uses URLSafe base64 encoding without padding: https://www.w3.org/TR/webauthn/#sctn-dependencies.

However, I see no issue with just stripping the padding characters (if they are there) when unmarshalling. Would that work for you? See https://github.com/bas-d/appattest/pull/3

**Comment by apryiomka** [comment]
@bas-d Appreciate the fix much!!!!
